name: Update

on: 
  workflow_dispatch:
    inputs:
      URL:
        type: string
        description: URL of pdfjs from mozilla
        default: 'https://github.com/mozilla/pdf.js/releases/download/v4.7.76/pdfjs-4.7.76-dist.zip'
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_PAT }}

      - name: Run
        run: |
          rm -rf web build LICENSE
          wget "$URL" && unzip "$(basename "$URL")" && rm "$(basename "$URL")"
        env:
          URL: ${{ github.event.inputs.URL }}

      - name: Commit and Push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "Run a.sh and update files" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
